#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2018-10-18 16:36:47
# @Author  : Will Wei (weixl5@asiainfo.com)
# @Version : 1.0.0_beta
# @Description : Test Case

import os
import unittest
import xlrw.xlrw

class TestCellFormat(unittest.TestCase):
	"""
	Traverse to compare cells in new workbook with template excel
	
	"""
	def __init__(self, tmpl, result):
		self.__tmpl = tmpl
		self.__result = result

	def test_traverse_cells(self):
		self.assertEqual(1, 1)

if __name__ == '__main__':
		unittest.main()
